# Generated by Django 5.2.8 on 2025-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
